### ISSUE TITLE
Siteswap Bot does not have a licence 

### ISSUE THREAD

**Issue by ambuc** [loganstafman/siteswap-bot#1]
Juggling Lab is GNU licenced according to its `README.md`, but the enclosing `siteswap-bot` repo has no declared licence. I'd like to use this in a siteswap-related project, and would like to make sure it has your blessing.

–J

**Comment by loganstafman** [comment]
I just added the COPYING.txt from the modified JugglingLab repo which is located in my repo.  Is that enough? I never deal with licences really.  Feel free to use as you wish.
